### ISSUE TITLE
mixed names of breakpoints

### ISSUE THREAD

**Issue by hans2103** [timble/illusion#18]
the current names of the breakpoints are:
https://github.com/timble/illusion/blob/01c0db78a8bdf85fb368093b5d256fc7923a9b48/scss/tools/variables/_breakpoints.scss#L4-L18

This seems like the Greek alphabet, but it fails on _Charlie_ which is part of the NATO alphabet. 

- https://en.wikipedia.org/wiki/NATO_phonetic_alphabet
- https://en.wikipedia.org/wiki/Greek_spelling_alphabet

Choose one, not both. 
I suggest to choose for the NATO phonetic alphabet. 
Alfa, Bravo, Charlie, Delta, Echo

This needs a refactor of the framework. I'll create a PR.

**Comment by hans2103** [comment]
created PR "mixed names of breakpoints" #19

**Comment by robinpoort** [comment]
Fixed in https://github.com/timble/illusion/releases/tag/v3.0.0
