### ISSUE TITLE
Remove vendor prefix for box-sizing

### ISSUE THREAD

**Issue by tomjanssens** [timble/illusion#20]
When using autoprefixer it removes the vendor prefixes for `box-sizing` when configured with:

```
options: {
  browsers: ['> 5% in BE', '> 5% in NL']
}
```

Suggest to remove them from Illusion.

**Comment by robinpoort** [comment]
@tomjanssens Where'd you find box-sizing prefixes in Illusion?

**Comment by tomjanssens** [comment]
My bad, it was in an old version.
